import {StyleSheet} from 'react-native';
import {RFS, hp, iosPAD, wp} from '../../dimensions/dimensions';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  bgWrap: {
    flex: 1,
    backgroundColor: 'white',
    width: '100%',
    height: '80%',
  },
  moreDetailsTitle: {
    fontSize: RFS(30),
    color: '#3291EA',
    textAlign: 'center',
    lineHeight: 44,
    // fontWeight: 'bold',
    marginTop: hp(7),
    fontFamily: 'Assistant-Bold',
  },
  moreDetailsSubtitle: {
    fontSize: RFS(22),
    lineHeight: 40,
    color: '#3291EA',
    textAlign: 'center',
    fontFamily: 'Assistant-Regular',
  },
  input: {
    height: 30,
    fontSize: RFS(16),
    // padding: 10, // borderColor: "#bbb",
    // borderWidth: 1,
    // marginBottom: 10,
    // paddingLeft: 15,
    // paddingRight: 15,
    // borderRadius: 10,
    // backgroundColor: "#F8FAFC",
    // marginHorizontal: 20,
    // textAlign: 'right',
    color: 'black',
  },
  submitButton: {
    borderRadius: 100,
    width: 200,
    marginTop: 30,
    backgroundColor: '#3291EA',
    alignSelf: 'center',
  },
  submitButtonText: {
    color: 'white',
    fontSize: RFS(20),
    textAlign: 'center',
    padding: 15,
    fontFamily: 'Assistant-Bold',
  },
  errorText: {
    color: 'red',
    textAlign: 'center',
    fontSize: RFS(18),
    fontFamily: 'Assistant',
  },
  emailContainer: {
    height: iosPAD ? hp(8) : hp(7),
    width: wp(90),
    backgroundColor: '#F7F7F8',
    borderRadius: 10,
    paddingRight: wp(4),
    alignSelf: 'center',
    justifyContent: 'center',
    marginBottom: hp(2),
    // alignItems: 'flex-end',
    paddingBottom: hp(0),
  },
  headingText: {
    color: '#939393',
    fontSize: RFS(9),
    fontFamily: 'Assistant-Regular',
    marginLeft: 10,
  },
  valueText: {
    color: 'black',
    fontSize: RFS(16),
    lineHeight: 20,
    fontFamily: 'Assistant-Regular',
    marginTop: 5,
  },
  buttonContainer: {
    alignSelf: 'center',
    marginBottom: hp('5%'),
  },
  button: {
    paddingHorizontal: wp(5),
    backgroundColor: '#0A84FF',
    height: hp(6),
    width: wp(40),
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: hp(10),
    marginTop: hp(4),
  },
  deleteText: {
    fontWeight: '600',
    fontSize: RFS(16),
    fontFamily: 'Assistant-Regular',
    color: 'white',
  },
  line: {
    height: hp(2),
    width: wp(0.3),
    backgroundColor: '#0A84FF',
    marginHorizontal: wp(5),
  },
  termsConditions: {
    color: '#0A84FF',
    fontSize: RFS(12),
    lineHeight: 20,
    fontFamily: 'Assistant-Regular',
    // marginTop: 5,
  },
  termsConditionContainer: {
    flexDirection: 'row',
    marginTop: hp(3),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  imageContainer: {
    height: iosPAD ? hp(15) : 100,
    width: iosPAD ? hp(15) : 100,
    alignSelf: 'center',
    marginVertical: 30,
  },
  userImage: {
    height: iosPAD ? hp(15) : 100,
    width: iosPAD ? hp(15) : 100,
    borderRadius: 100,
    alignSelf: 'center',
  },
  refreshImage: {
    height: 30,
    width: 30,
    position: 'absolute',
    bottom: 0,
    right: 0,
  },
  signUpText: {
    marginLeft: hp(0.5),
    color: '#3389e9',
    fontSize: RFS(14),
  },
  checkBoxContainer: {
    marginRight: wp(5),
    height: 'flex',
    height: iosPAD ? hp(8) : hp(7),
  },
  checkText: {
    marginLeft: wp(1),
    fontSize: RFS(12),
    fontWeight: '400',
    marginRight: wp(1),
  },
});

export default styles;
