import {Platform, StyleSheet} from 'react-native';
import {RFS, hp, iosPAD, isPAD, wp} from '../../dimensions/dimensions';

export default styles = StyleSheet.create({
  mainContainer: {
    // backgroundColor: "brown",
    flex: 1,
    backgroundColor: 'white',
  },
  wrapWith: {
    flex: 1,
    marginTop: hp(5),
  },
  userInformationContainer: {
    backgroundColor: 'brown',
  },
  dropdownContainer: {
    marginTop: Platform.OS === 'ios' ? hp(0) : hp(0),
    paddingHorizontal: wp(5),
  },
  languageChangeContainer: {
    marginTop: hp(2),
    alignItems: 'flex-end',
    backgroundColor: '#00000020',
    width: wp(82),
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 10,
  },
  englishContainer: {
    marginTop: hp(2),
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  hebrewContainer: {
    marginTop: 5,
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  hebrewText: {
    fontSize: RFS(12),
    fontWeight: '500',
    color: '#00000090',
  },
  englishText: {
    fontSize: RFS(13),
    fontWeight: '500',
    color: '#00000090',
  },
  selectText: {
    fontSize: RFS(11),
    fontWeight: 'bold',
    color: '#000000',
  },
  englishText: {
    fontSize: RFS(13),
    fontWeight: '500',
    color: '#00000090',
  },
  imageStyle: {
    height: hp(10),
    width: hp(10),
  },
  languageText: {
    fontSize: RFS(16),
    fontWeight: 'bold',
    marginBottom: hp(1),
    color: 'black',
  },
  buttonContainer: {
    alignSelf: 'center',
  },
  button: {
    marginTop: hp(5),
    paddingHorizontal: wp(5),
    backgroundColor: '#AEAEAE',
    height: iosPAD ? hp(6) : hp(5),
    // width: wp(40),
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: hp(10),
    // marginTop: hp(2),
  },
  disconnectButton: {
    paddingHorizontal: wp(9),
    backgroundColor: '#FA5656',
    height: iosPAD ? hp(6) : hp(5.5),
    // width: wp(40),
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: hp(10),
    marginTop: hp(2),
  },
  logoutText: {
    color: 'white',
    fontSize: RFS(16),
  },
  cancelContainer: {
    top: isPAD ? hp(1) : hp(2),
    marginTop: hp(5),
    paddingHorizontal: hp(2),
    alignItems: 'flex-end',
    marginBottom: hp(3),
    ...(isPAD && {left: -10}),
  },
  root: {
    flex: 1,
    backgroundColor: 'white',
  },
  bgWrap: {
    // flex: 1,
    width: '100%',
    height: '80%',
    position: 'absolute',
    // top: 0,
    // backgroundColor: 'red',
  },
  cancelText: {
    fontSize: RFS(14),
    color: 'red',
  },
  definitionsContainer: {
    marginTop: hp(2),
  },
  definitionsText: {
    fontSize: RFS(25),
    fontWeight: '700',
    textAlign: 'center',
    fontFamily: 'Assistant-Regular',
    color: '#155B96',
    ...(!isPAD && {lineHeight: 32}),
  },
  infoContainer: {
    height: iosPAD ? hp(7) : hp(7),
    width: wp(90),
    backgroundColor: '#F7F7F8',
    borderRadius: 20,
    marginVertical: hp(2),
    alignSelf: 'center',
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingRight: wp(4),
  },
  imageContainerMain: {
    flexDirection: 'row-reverse',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  imageContainer: {
    marginRight: wp(4),
    backgroundColor: '#00000020',
    height: hp(5),
    width: hp(5),
    borderRadius: 100,
    // backgroundColor: 'red',
    // paddingVertical: hp(1),
  },
  refreshImage: {
    height: hp(2),
    width: hp(2),
    resizeMode: 'contain',
    position: 'absolute',
    bottom: 0,
    right: 0,
  },
  userName: {
    fontSize: RFS(15),
    fontWeight: '600',
    textAlign: 'center',
    fontFamily: 'Assistant-Regular',
    color: 'black',
    marginRight: wp(4),
  },
  userImage: {
    height: hp(5),
    width: hp(5),
    borderRadius: 100,
    resizeMode: 'contain',
  },
  emailContainer: {
    height: iosPAD ? hp(7) : hp(7),
    width: wp(90),
    backgroundColor: '#F7F7F8',
    borderRadius: 20,
    paddingRight: wp(4),
    alignSelf: 'center',
    justifyContent: 'center',
    marginBottom: hp(2),
    alignItems: 'flex-end',
  },
  cityContainer: {
    height: isPAD ? hp(7) : hp(7),
    width: wp(90),
    backgroundColor: '#F7F7F8',
    borderRadius: 20,
    paddingHorizontal: wp(4),
    alignSelf: 'center',
    justifyContent: 'space-between',
    marginBottom: hp(2),
    alignItems: 'center',
    flexDirection: 'row-reverse',
  },
  languageContainer: {
    // height: hp(7),
    paddingVertical: isPAD ? hp(2) : 6,
    width: wp(90),
    backgroundColor: '#F7F7F8',
    borderRadius: 20,
    paddingRight: wp(4),
    alignSelf: 'center',
    justifyContent: 'center',
    marginBottom: hp(2),
    alignItems: 'flex-end',
  },
  headingText: {
    color: '#939393',
    fontSize: RFS(9),
    fontFamily: 'Assistant-Regular',
    textAlign: 'right',
  },
  changeText: {
    color: '#155B96',
    fontSize: RFS(10),
    fontFamily: 'Assistant-Regular',
    textAlign: 'right',
  },
  valueText: {
    color: 'black',
    fontSize: RFS(13),
    ...(!iosPAD && {lineHeight: 20}),
    fontFamily: 'Assistant-Bold',
    ...(!iosPAD && {marginTop: Platform.OS === 'ios' ? 10 : 10}),
  },
  flagImage: {
    height: hp(2),
    width: hp(2),
    marginRight: 5,
    borderRadius: 10,
  },
  flagContainer: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteText: {
    fontWeight: '600',
    fontSize: RFS(13),
    fontFamily: 'Assistant-Regular',
    color: '#FFFFFF',
  },
  line: {
    height: hp(2),
    width: wp(0.3),
    backgroundColor: '#0A84FF',
    marginHorizontal: wp(5),
  },
  termsConditions: {
    color: '#0A84FF',
    fontSize: RFS(14),
    lineHeight: 20,
    fontFamily: 'Assistant-Regular',
    // marginTop: 5,

  },
  termsConditionContainer: {
    flexDirection: 'row',
    marginTop: hp(2),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  input: {
    fontSize: RFS(14),
    paddingRight: 0,
    textAlign: 'right',
    color: 'black',
    paddingVertical: 0,
  },
  inputBlur: {
    fontSize: RFS(14),
    paddingRight: 0,
    textAlign: 'right',
    color: 'black',
    paddingVertical: 0,
  },
});
